version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'saturday'
      time: '09:00'
      timezone: 'UTC'
    open-pull-requests-limit: 10
    # groups:
    #   dependencies:
    #     patterns:
    #       - '*'
    commit-message:
      prefix: 'chore'
      prefix-development: 'chore'
      include: 'scope'

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'saturday'
      time: '09:00'
      timezone: 'UTC'
    open-pull-requests-limit: 10
    commit-message:
      prefix: 'ci'
      include: 'scope'
